/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root.tsx";

// Create Virtual Routes

const ProductsLazyImport = createFileRoute("/products")();
const ProductDetailLazyImport = createFileRoute("/product-detail")();
const MerchantDashboardLazyImport = createFileRoute("/merchant-dashboard")();
const EditProductLazyImport = createFileRoute("/edit-product")();
const CreateShopLazyImport = createFileRoute("/create-shop")();
const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const ProductsLazyRoute = ProductsLazyImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/products.lazy.tsx").then((d) => d.Route));

const ProductDetailLazyRoute = ProductDetailLazyImport.update({
  id: "/product-detail",
  path: "/product-detail",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/product-detail.lazy.tsx").then((d) => d.Route)
);

const MerchantDashboardLazyRoute = MerchantDashboardLazyImport.update({
  id: "/merchant-dashboard",
  path: "/merchant-dashboard",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/merchant-dashboard.lazy.tsx").then((d) => d.Route)
);

const EditProductLazyRoute = EditProductLazyImport.update({
  id: "/edit-product",
  path: "/edit-product",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/edit-product.lazy.tsx").then((d) => d.Route)
);

const CreateShopLazyRoute = CreateShopLazyImport.update({
  id: "/create-shop",
  path: "/create-shop",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/create-shop.lazy.tsx").then((d) => d.Route)
);

const IndexLazyRoute = IndexLazyImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy.tsx").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/create-shop": {
      id: "/create-shop";
      path: "/create-shop";
      fullPath: "/create-shop";
      preLoaderRoute: typeof CreateShopLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/edit-product": {
      id: "/edit-product";
      path: "/edit-product";
      fullPath: "/edit-product";
      preLoaderRoute: typeof EditProductLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/merchant-dashboard": {
      id: "/merchant-dashboard";
      path: "/merchant-dashboard";
      fullPath: "/merchant-dashboard";
      preLoaderRoute: typeof MerchantDashboardLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/product-detail": {
      id: "/product-detail";
      path: "/product-detail";
      fullPath: "/product-detail";
      preLoaderRoute: typeof ProductDetailLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/products": {
      id: "/products";
      path: "/products";
      fullPath: "/products";
      preLoaderRoute: typeof ProductsLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/create-shop": typeof CreateShopLazyRoute;
  "/edit-product": typeof EditProductLazyRoute;
  "/merchant-dashboard": typeof MerchantDashboardLazyRoute;
  "/product-detail": typeof ProductDetailLazyRoute;
  "/products": typeof ProductsLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/create-shop": typeof CreateShopLazyRoute;
  "/edit-product": typeof EditProductLazyRoute;
  "/merchant-dashboard": typeof MerchantDashboardLazyRoute;
  "/product-detail": typeof ProductDetailLazyRoute;
  "/products": typeof ProductsLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexLazyRoute;
  "/create-shop": typeof CreateShopLazyRoute;
  "/edit-product": typeof EditProductLazyRoute;
  "/merchant-dashboard": typeof MerchantDashboardLazyRoute;
  "/product-detail": typeof ProductDetailLazyRoute;
  "/products": typeof ProductsLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/create-shop"
    | "/edit-product"
    | "/merchant-dashboard"
    | "/product-detail"
    | "/products";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/create-shop"
    | "/edit-product"
    | "/merchant-dashboard"
    | "/product-detail"
    | "/products";
  id:
    | "__root__"
    | "/"
    | "/create-shop"
    | "/edit-product"
    | "/merchant-dashboard"
    | "/product-detail"
    | "/products";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  CreateShopLazyRoute: typeof CreateShopLazyRoute;
  EditProductLazyRoute: typeof EditProductLazyRoute;
  MerchantDashboardLazyRoute: typeof MerchantDashboardLazyRoute;
  ProductDetailLazyRoute: typeof ProductDetailLazyRoute;
  ProductsLazyRoute: typeof ProductsLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CreateShopLazyRoute: CreateShopLazyRoute,
  EditProductLazyRoute: EditProductLazyRoute,
  MerchantDashboardLazyRoute: MerchantDashboardLazyRoute,
  ProductDetailLazyRoute: ProductDetailLazyRoute,
  ProductsLazyRoute: ProductsLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-shop",
        "/edit-product",
        "/merchant-dashboard",
        "/product-detail",
        "/products"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/create-shop": {
      "filePath": "create-shop.lazy.tsx"
    },
    "/edit-product": {
      "filePath": "edit-product.lazy.tsx"
    },
    "/merchant-dashboard": {
      "filePath": "merchant-dashboard.lazy.tsx"
    },
    "/product-detail": {
      "filePath": "product-detail.lazy.tsx"
    },
    "/products": {
      "filePath": "products.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
