import { defineConfig, PluginOption } from "vite";
import deno from "@deno/vite-plugin";
import react from "@vitejs/plugin-react";
import { TanStackRouterVite } from "@tanstack/router-plugin/vite";
import tailwindcss from "tailwindcss";
import { nodePolyfills } from "vite-plugin-node-polyfills";
import { routeTree } from "./src/routeTree.gen.ts";

// Take all the routes and create an object with the route name as the key and the index.html as the value.
// The html files are generated by the generate-entry-points.ts script.
const entryPoints = Object.values(routeTree.children || {})
  .map((r) => r.options.path.slice(1))
  .slice(1);
const buildInputs = Object.fromEntries(
  entryPoints.map((path) => [path, "index.html"]),
);

export default defineConfig({
  css: {
    postcss: {
      plugins: [tailwindcss()],
    },
  },
  build: {
    rollupOptions: {
      input: buildInputs,
    },
    outDir: "dist",
    copyPublicDir: true,
  },

  plugins: [
    deno(),
    react(),
    TanStackRouterVite({ addExtensions: true }),
    nodePolyfills() as PluginOption,
  ],
});
